/*
  Don't edit.
  Code generated by jemo.py.
*/

import 'dart:convert';
import 'XXX456';
import 'XXX123';

class First extends SuperFirst {
    double? aaa;
    bool b;
    SubC ccc;
    List<SubItem1>? fff;
    List<YZ> x;

    First({
        this.aaa,
        required this.b,
        required this.ccc,
        this.fff,
        required this.x,
    });

    factory First.fromRawJson(String str) => First.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory First.fromJson(Map<String, dynamic> json) => First(
        aaa: json['a']?.toDouble(),
        b: json['b'],
        ccc: SubC.fromJson(json['c']),
        fff: json['f'] != null ? List<SubItem1>.from(json['f'].map((e) => SubItem1.fromJson(e))) : null,
        x: List<YZ>.from(json['x'].map((e) => YZ.fromJson(e))),
    );

    Map<String, dynamic> toJson() => {
        "a": aaa,
        "b": b,
        "c": ccc.toJson(),
        "f": fff != null ? List<dynamic>.from(fff!.map((e) => e.toJson())) : null,
        "x": List<dynamic>.from(x.map((e) => e.toJson())),
    };
}

class SubC {
    Inc? inc;
    int d;
    String e;

    SubC({
        this.inc,
        required this.d,
        required this.e,
    });

    factory SubC.fromRawJson(String str) => SubC.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory SubC.fromJson(Map<String, dynamic> json) => SubC(
        inc: json['i'] != null ? Inc.fromJson(json['i']) : null,
        d: json['d'],
        e: json['e'],
    );

    Map<String, dynamic> toJson() => {
        "i": inc?.toJson(),
        "d": d,
        "e": e,
    };
}

class Inc {
    String k;
    String n;

    Inc({
        required this.k,
        required this.n,
    });

    factory Inc.fromRawJson(String str) => Inc.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory Inc.fromJson(Map<String, dynamic> json) => Inc(
        k: json['k'],
        n: json['n'],
    );

    Map<String, dynamic> toJson() => {
        "k": k,
        "n": n,
    };
}

class SubItem1 {
    int g;
    int h;

    SubItem1({
        required this.g,
        required this.h,
    });

    factory SubItem1.fromRawJson(String str) => SubItem1.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory SubItem1.fromJson(Map<String, dynamic> json) => SubItem1(
        g: json['g'],
        h: json['h'],
    );

    Map<String, dynamic> toJson() => {
        "g": g,
        "h": h,
    };
}

class YZ {
    int y;
    bool z;

    YZ({
        required this.y,
        required this.z,
    });

    factory YZ.fromRawJson(String str) => YZ.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory YZ.fromJson(Map<String, dynamic> json) => YZ(
        y: json['y'],
        z: json['z'],
    );

    Map<String, dynamic> toJson() => {
        "y": y,
        "z": z,
    };
}

class Second extends SuperSecond {
    String username;
    String password;
    SubC ccc;

    Second({
        required this.username,
        required this.password,
        required this.ccc,
    });

    factory Second.fromRawJson(String str) => Second.fromJson(json.decode(str));

    String toRawJson() => json.encode(toJson());

    factory Second.fromJson(Map<String, dynamic> json) => Second(
        username: json['user_name'],
        password: json['password'],
        ccc: SubC.fromJson(json['duplicateModel']),
    );

    Map<String, dynamic> toJson() => {
        "user_name": username,
        "password": password,
        "duplicateModel": ccc.toJson(),
    };
}
